apiVersion: v1
kind: Service
metadata:
  name: nexus
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"                     # Use NLB (not ELB)
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" 
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-0d9319bec53a522f7,eipalloc-085c4682c4a0b6cb4"# Make it public
spec:
  type: LoadBalancer
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081  # Assuming Nexus is running on port 8081 inside the container
