nexus:
  image: sonatype/nexus3:latest
  service:
    type: LoadBalancer
    port: 8081
  storage:
    size: 10Gi

postgresql:
  image: postgres:15
  username: nexus
  password: nexuspassword
  database: nexusdb
  service:
    type: ClusterIP
    port: 5432
  storage:
    size: 10Gi

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: nexus.cloudmasa.com
  tls:
    - hosts:
        - nexus.cloudmasa.com
      secretName: nexus-tls
